### ISSUE TITLE
Figure out UX & treatment for indicating activity flow & linking them together

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#10]
We have a couple of ways where we do this now.. 

**Beginning of an activity**
![image](https://cloud.githubusercontent.com/assets/25212/18644395/1f4ac2aa-7e5e-11e6-85ad-92f8ee9e910e.png)

**End of an activity**
![image](https://cloud.githubusercontent.com/assets/25212/18644387/15930394-7e5e-11e6-961e-447b7c993d16.png)

**Comment by flukeout** [comment]
I took another stab at the activity meta data, and came up with a simplified approach that makes use of our basic bulleted lists...

![image](https://cloud.githubusercontent.com/assets/25212/18855596/01691376-8409-11e6-904e-6cc98650b54a.png)

Not as flashy, but also not as distracting. Thoughts, @chadsansing?

**Comment by chadsansing** [comment]
Get the job done, but adds a lot of bullets. Seeing so many together makes me miss the button-like treatment of the skills a bit, but I think this will work for a page full of meta-information. 

What if we made the 21st C skills back into button-like things, treated Read, Write, and Participate with a slightly different style to separate them visually from the skills the encompass, and also put the Learn More under each?

**Comment by flukeout** [comment]
Learn more under each of Read, Write & Participate?

I'll try some other stuff, not really sold on this treatment either - stay tuned!

**Comment by chadsansing** [comment]
At the bottom of the Read, Write, Participate section - once.

Attuned!

**Comment by flukeout** [comment]
What about this kind of hairarchy / grouping

<img width="494" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18883577/a2b771e8-8498-11e6-9cca-156add481f83.png">

**Comment by chadsansing** [comment]
Closer for sure. 21st C Skills needs to be a sibling of Web Literacy Skills, in my mind.

**Comment by flukeout** [comment]
Hmm, okay, let me try something different then.. in the meantime, slightly less clunky maybe..

<img width="537" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18884298/acad1876-849b-11e6-9951-3520946841cf.png">

Will return with sibling-ized skills

**Comment by chadsansing** [comment]
After talking w/ An-Me, I also wonder if we can link these back to their skills pages or to the badges (e.g. the Navigate button goes to https://learning.mozilla.org/en-US/web-literacy/read/navigate/).

**Comment by flukeout** [comment]
Link each individual skill listed? Sure, i can give it a shot

Was working on this treatment in the meantime...

<img width="558" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18886216/df0fff7e-84a3-11e6-86ed-1d5b4c7e53b6.png">

**Comment by chadsansing** [comment]
Nice - feeling this one.

**Comment by flukeout** [comment]
So something like...

<img width="572" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18886347/6467d822-84a4-11e6-9538-f745d06b788a.png">

It could work, not sure how useful it would be to have them all link. I guess once you clicked one, you wouldn't go back and click another one. Also a lot of markup to maintain all the links in the activity.

**Comment by chadsansing** [comment]
Exactly. You don't like the old button colors? ;)

**Comment by flukeout** [comment]
Do you like your eyes bleeding? 

<img width="534" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18886457/d1c19778-84a4-11e6-98c0-73b4ad45441c.png">

**Comment by flukeout** [comment]
Anyway, the button styling (color etc) is pretty easy to change in the CSS later, are you digging the general layout?

**Comment by chadsansing** [comment]
I am!

**Comment by flukeout** [comment]
Okay, going with something like this for now...

<img width="550" alt="image" src="https://cloud.githubusercontent.com/assets/25212/18889004/b6eea980-84af-11e6-8828-94aaa6a79813.png">

Will focus on the next / previous activities now and then we can call the design work DONE!

**Comment by flukeout** [comment]
Closing this as we'll stick with the skills treatment above. Will open a new issue for next / previous activities.
