### ISSUE TITLE
Design navigation between activities in a module.

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#14]
Got some feedback and here's the current thinking: a dropdown style menu that appears at the top of the overview page for an activity in a module. Here's how it looks & works...

![activity-menu](https://cloud.githubusercontent.com/assets/25212/18895352/dd8db130-84cd-11e6-85cc-b1cf53fefbb7.gif)

**Try it out** - https://mozilla.github.io/curriculum-final/blank-template/#overview

Styling still need work (and mobile) - but general idea is there.

cc @chadsansing - thoughts?

**Comment by flukeout** [comment]
Disregard the weird grey / white stuff - just came out weird in the gif, looks like this...

![image](https://cloud.githubusercontent.com/assets/25212/18895372/04eac29a-84ce-11e6-9fd2-eab6922c7d90.png)

**Comment by chadsansing** [comment]
Works for me - I like that it feels webby.

**Comment by flukeout** [comment]
Here's the mobile treatment @chadsansing ...

![mobile-menu](https://cloud.githubusercontent.com/assets/25212/18923603/c1765d28-8561-11e6-8c12-49f44e35f5fe.gif)

**Comment by chadsansing** [comment]
Love it - love the .gif illustrations, too!

**Comment by flukeout** [comment]
Cool. Yeah, they're handy - I was using LiceCAP (http://www.cockos.com/licecap/) but today I just bought Gifox (http://gifox.io/) - so far it seem really good and its $3.99

**Comment by chadsansing** [comment]
I need one. I'll check it out! We should also design a branching .gif game or something to teach about image formats for the web.

**Comment by flukeout** [comment]
Gifox is way better than licecap, give it a try - better framerate and less weird artifacts (he said after using it to make one gif)

**Comment by flukeout** [comment]
Anyway, will close this now and polish this stuff up. Once it's ready we can audit
