### ISSUE TITLE
Review final design

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#15]
Hey @chadsansing the Blank Template has all of the latest styling, please check it out here...
- https://mozilla.github.io/curriculum-final/blank-template/

Let me know your thoughts & feedback. Once we finalize this one we can apply these styles to the rest of the content in the repo.

**Comment by chadsansing** [comment]
Looks good; let's also see what An-Me think of the Web Lit and 21st C Skills treatments?

Where would we anticipate tags going once we add them? After the 21st C Skills?

**Comment by flukeout** [comment]
DAMNIT, I forgot about tags! AHHHHH.

Anyway, about tags - we'll probably make them unlinked, since we don't really have a way to do anything if you click them. So just a quick little list somewhere maybe. I feel like it's more of a search tool than something you care about when looking at the activity?

**Comment by chadsansing** [comment]
Agreed, unless we want to make affordances for seeing other activities and user-curated collections by tag at some point down the road.

**Comment by flukeout** [comment]
So maybe we won't bother listing them on the activity itself then? They only provide vague meta-info and won't be clickable.

**Comment by chadsansing** [comment]
What I mean is, if we make them visible, then maybe one day they could be clickable to see other activities with the same tag?

**Comment by flukeout** [comment]
Yeah, but then we'd have to go and edit every activity to make those links work, so we might as well save the work for when we can get the benefit from it? I also don't know what all the tags for each activity are, are they listed somewhere?

**Comment by chadsansing** [comment]
You mean there's no magic way to make all alike tag talk with one another? Script the CSS nodules thusly!

I hear you. I think we should make tags visible, if not functional, to help people find key words during searches - like the IMLS folk would benefit from #imls #libraries, etc.

**Comment by flukeout** [comment]
In the activity database, the tags will be in there, so along with a link to a piece of curriculum will be a list of tags. The activities will be searchable via tags, and the tags will show up with each search result. In addition to that, if you want, we can add that list of tags to the actual activity content - it just doesn't seem to provide any value once you actually get to the activity.

Your call though! We can try tagging a few and see how it feels. Do you want to pick a couple activities in the current set and give me a list of tags for each?

**Comment by flukeout** [comment]
In the meantime, I'm goint to link all of the skills tags to their spot on the web lit map.

**Comment by chadsansing** [comment]
Okay - I get it better now. I think there's something to visual affirmation for users looking for clues from other users on the page, but my primary concern is discoverability by search. 

Let's try this without the tags on the page.

**Comment by flukeout** [comment]
Sounds good, another Q, what order do you want the skill types listed? We have Read, Write & Participate right now, but on the web lit map they are "Write, Read & Participate"

**Comment by flukeout** [comment]
Also, shoot, we don't have a way to link "Collaboration" directly to that skill, we have just have main 21C skills page here - https://learning.mozilla.org/en-US/web-literacy/skills - I can link them all there until we figure out something better?

**Comment by flukeout** [comment]
I was wrong, we can - https://learning.mozilla.org/en-US/web-literacy/skills#problem-solving woooop!

**Comment by chadsansing** [comment]
R --> W --> P.

**Comment by flukeout** [comment]
Closing this - we'll be moving forward with the styling in the template.
