### ISSUE TITLE
Apply new styling & markup to an activity.

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#16]
@chadsansing can you apply the new markup for the skills to an existing activity?
- Use the skills list markup from the `/blank-template`
  - https://mozilla.github.io/curriculum-final/blank-template/
- Apply it to the `encryption/really-private-messaging` activity
  - https://mozilla.github.io/curriculum-final/encryption/really-private-messaging.html

Take a crack at it and let me know how it goes.

**Comment by chadsansing** [comment]
Finished. Starting a new ticket to track progress on the rest of the modules.
