### ISSUE TITLE
Add new styling and markup to all modules

### ISSUE THREAD

**Issue by chadsansing** [mozilla/curriculum-final#17]
Let's track which modules we've revised to include the new styling and mark-up schemes for navigation and skills.
- [x] Encryption
- [x] Intermediate Web Lit I
- [x]  Intermediate Web Lit II
- [x] Kenya DSO Interventions
- [x] Offline Icebreakers
- [x] Web Lit Basics I
- [x] Web Lit Basics II
- [x] What if they had the web?
- [x] Make Your First Webpage

cc @flukeout

**Comment by chadsansing** [comment]
See #18 for adding Make Your First Webpage.

**Comment by chadsansing** [comment]
@flukeout - a number of these have been updated. Could you test a few when you have the chance to make the sure the nav scheme and new nav/skills links work?

**Comment by flukeout** [comment]
Yeah, will do some of that now.

**Comment by chadsansing** [comment]
Thanks, @flukeout!

**Comment by flukeout** [comment]
Reviewed & cleaned up so far...
- Encryption
- Web Lit Basics I

Here are some thoughts...
- Skills and activity menu stuff looks good and works
- Had to clean up a lot of indentation
  - We should be pretty strict on this as it makes the code more readable
  - It's easier to remix when well indented
  - I can look around for a tool that can clean up / auto-indent our stuff
- Let's use the standard `.up-next` markup from the blank template for linking to the next activity

It's pretty time consuming to do this, will need to take a break and return to it later.

**Comment by chadsansing** [comment]
I think we're done here.
