### ISSUE TITLE
Fix sidebar size jump

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#19]
Visible here on the jump between overview and step 1 in [this activity](https://mozilla.github.io/curriculum-final/encryption/werewolf-in-the-middle.html#overview).

![size-jump](https://cloud.githubusercontent.com/assets/25212/19161774/01e6fd24-8baa-11e6-9b2a-3cb231825d47.gif)

**Comment by chadsansing** [comment]
Here also:

- https://mozilla.github.io/curriculum-final/internet-health-basics/session03-digital-inclusion.html#overview
- https://mozilla.github.io/curriculum-final/internet-health-basics/session04-privacy-and-security.html#overview
- https://mozilla.github.io/curriculum-final/internet-health-basics/session06-open-innovation.html#step-1

Any progress, @flukeout? Is the quick fix in the meantime to add empty paragraphs and extend the main column content to lock the sidebar?

**Comment by flukeout** [comment]
Will check in on this later today.
