### ISSUE TITLE
For optional issues use the following markup

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#21]
Instead of this

![image](https://cloud.githubusercontent.com/assets/25212/19163207/f5ef22ca-8baf-11e6-92b6-845ce46a1b67.png)

Do this...

![image](https://cloud.githubusercontent.com/assets/25212/19163287/3592aae6-8bb0-11e6-9092-c0ac3cec9a2d.png)

It will appear as...

![image](https://cloud.githubusercontent.com/assets/25212/19163252/1c379b60-8bb0-11e6-82f3-89134006bcda.png)

It styles it and adds Optional at the end. @chadsansing close when you've read this. Should we put "Opitonal:" in front instead?

**Comment by chadsansing** [comment]
Yes to optional in-front.
