### ISSUE TITLE
For next activity, use following markup

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#22]
Instead of this..

![image](https://cloud.githubusercontent.com/assets/25212/19163747/14f2dd04-8bb2-11e6-86a1-3045dd80ddd9.png)

Use this

![image](https://cloud.githubusercontent.com/assets/25212/19163762/1ee65714-8bb2-11e6-9bef-7a4869f91b2b.png)

It will appear as...

![image](https://cloud.githubusercontent.com/assets/25212/19163774/2e94678c-8bb2-11e6-87e9-8beedd235078.png)

@chadsansing close when read.

**Comment by chadsansing** [comment]
Got it.
