### ISSUE TITLE
Session number mismatch

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#23]
Hey @chadsansing in web lit basics 1, there's a Thimble activity (#3) and it makes it so that by activity 4, the number in the address bar and the activity title doesn't match...

![image](https://cloud.githubusercontent.com/assets/25212/19166314/e17eee0e-8bbb-11e6-948f-223a59b4f7af.png)

Doesn't feel right, what do you think. Is it worth putting the Thimble one in the dropdown menu? Is it useful stand-alone?

**Comment by chadsansing** [comment]
If we can find an acceptable way to err on the side of including it, I'd love to just to make sure people know about it at a glance. Not crucial, but desirable.

**Comment by flukeout** [comment]
I could look at including it as a sub-item in the activity menu, will get back to you.

**Comment by flukeout** [comment]
What about something like this

![image](https://cloud.githubusercontent.com/assets/25212/19174111/572737ea-8be1-11e6-9157-1e02e1f08335.png)

**Comment by flukeout** [comment]
It would also be nice if we could pull this markup from one spot in the folder, and not have to hardcode it into every activity. I'll look into it.

**Comment by flukeout** [comment]
Alright, I found a solution to let us just load the same chunk of HTML from a file called `activity-menu.html`, it looks like this...

```
<a class="toggle"><strong>Intermediate Web Literacy I</strong> - Activity <span class="current-activity"></span> of 8</a>
<ol class="activity-list">
  <li><a href="#">CSS Pyramid</a></li>
  <li>
    <a href="session02-css-fonts.html">CSS Fonts</a> <br/>
    <span class="extension">Extension - <a href="https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22265/">Bridge to Infinity</a></span>
  </li>
  <li><a href="session03-css-circles.html">CSS Circles</a></li>
  <li><a href="session04-css-building-blocks.html">CSS Blocks</a></li>
  <li><a href="session05-css-decoration.html">CSS Decoration</a></li>
  <li><a href="session06-webotron-and-the-scrambled-divs.html">Webotron &amp; the Scrambled Divs</a></li>
  <li><a href="session07-external-css-tutorials.html">External CSS Tutorials</a></li>
</ol>
```

It takes that and puts it into this tag in the activity, which needs to be there...

`<div class="activity-menu" activity-number="1"></div>``

Then it highlights the activity based on the `activity-number` attribute.

**Comment by flukeout** [comment]
Let me know your thoughts, I can demo it to you tomorrow before we decide to pull the trigger on it.

**Comment by chadsansing** [comment]
The bulleted extension looks good - not grokking where to put the div, but happy to see it demoed. Thanks, @flukeout!

**Comment by flukeout** [comment]
Okay, check out this file @chadsansing... 

https://github.com/mozilla/curriculum-final/blob/gh-pages/intermediate-web-lit-one/activity-menu.js

So, if any folder has this file, called `activity-menu.js`, the activities within that folder will automatically get a menu added to the top.

**Comment by chadsansing** [comment]
This is probably a fringe case - likely there won't be extension activities framed as such in future modules developed in-house. Maybe we can just style this one in-line. I'm wonder how complex this becomes for others to remix if we make the menu in another file and not on each page. I apologize for not realizing this concern sooner, but I think the nav scheme needs to be on the page for remixers - let's just patch the extension activity here; I can avoid using i in the future.
