### ISSUE TITLE
New style of doing activity-menu

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#24]
For the activity menu...
![image](https://cloud.githubusercontent.com/assets/25212/19449243/9916cb72-9459-11e6-83f0-403bc8792232.png)

Instead of putting the activity menu markup into each session document like this...

![image](https://cloud.githubusercontent.com/assets/25212/19449193/60750932-9459-11e6-8491-6e2b9c0452fc.png)

We will now include an `activity-menu.js` file in the folder, which contains...

```
var title = "Intermediate Web Literacy I";
var activities = [
  {
    title : "CSS Pyramid",
    url: "session01-css-pyramid.html"
  },
  {
    title : "CSS Fonts",
    url: "session02-css-fonts.html",
    extension : {
      title: "Bridge to Infinity",
      url: "https://d157rqmxrxj6ey.cloudfront.net/chadsansing/22265/"
    }
  },
  {
    title : "CSS Circles",
    url: "session03-css-circles.html"
  },
  {
    title : "CSS Blocks",
    url: "session04-css-building-blocks.html"
  },
  {
    title : "CSS Decoration",
    url: "session05-css-decoration.html"
  },
  {
    title : "Webotron &amp; the Scrambled Divs",
    url: "session06-webotron-and-the-scrambled-divs.html"
  },
  {
    title : "External CSS Tutorials",
    url: "session07-external-css-tutorials.html"
  }
];
```

You can grab this from the `/blank-template` folder for future modules.

I'll convert the "Build your own webpage" module now.

This will save us a lot of time because we just have to edit one file and it will be included automatically.

**Comment by flukeout** [comment]
@chadsansing take a look at what's going on in ...

https://github.com/mozilla/curriculum-final/tree/gh-pages/make-your-first-webpage
- There's an `activity-menu.js` file, it's got:
  - The module title
  - All of the activity titles & links
- Any module with this file will automatically add an activity menu to the Overview step of each activity
  - You don't have to add any markup or code to the activity itself
- It figures out the session number by looking or `session_XX` in the URL, so let's make sure we continue using that convention
  - If we want a different convention, we'll have to update the code.

Any questions or concerns?

**Comment by chadsansing** [comment]
I understand now - thanks, @flukeout. Is the next step to put activity-menu.js in the assets folder and then add the file to all the lessons?

**Comment by chadsansing** [comment]
NVM ^^^^

Took me a while to grok the idea of not needing to add the code to each file. I got it now.

**Comment by flukeout** [comment]
Yeah, you got it - just one file per folder and we're good. You can use any of the `activity-menu.js` files as a template.

**Comment by flukeout** [comment]
Closing - let me know if you run into trouble.
