### ISSUE TITLE
Activity menu is wrong for intermediate-web-lit-one

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#29]
![image](https://cloud.githubusercontent.com/assets/25212/23677810/86d1873a-0336-11e7-805e-3c043b22855b.png)

Because the code looks for the number after "session" it gets confused when it sees the following...

```
 {
    title : "CSS Fonts",
    url: "session02-css-fonts.html"
  },
  {
    title: "CSS Fonts Extension Activity",
    url: "session02a-css-fonts-extension-activity.html"
  }
```

..one remedy would be to rename the ``02a`` one to ``03`` (and increment all the subsequent activities).

**Comment by chadsansing** [comment]
Fixed.
