### ISSUE TITLE
Add styling for "teacher notes" (migrated issue from curriculum-testing)

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#3]
Original issue by @LauraReynal

https://github.com/chadsansing/curriculum-testing/issues/434

**Comment by chadsansing** [comment]
Using the blockquote styling to make scripted parts pink, which leaves the facilitation notes in normal text. Does that work? Can we close?

cc @flukeout, @LauraReynal

**Comment by chadsansing** [comment]
We can re-open later as needed, especially if/after we rebrand the template.
