### ISSUE TITLE
Positioning and treatments for localization and remixes

### ISSUE THREAD

**Issue by chadsansing** [mozilla/curriculum-final#31]
@flukeout, we've added links from our current Web Lit Basics I lessons to the old copies so we can keep offering the localized versions of each activity.

We've also linked every lesson of our core Web Literacy curriculum to Thimble versions for users to remix.

![screen shot 2017-03-08 at 8 18 37 am](https://cloud.githubusercontent.com/assets/4128600/23705564/69424b08-03d8-11e7-82d8-4132d0682f7e.png)

Wondering if you have ideas about placement and treatments for those links.

cc @anmechung @ibgmozilla

**Comment by flukeout** [comment]
Hey @chadsansing can you link to the activity where these appear now?

**Comment by flukeout** [comment]
Nevermind, I can find it!

**Comment by chadsansing** [comment]
@flukeout, the localized links appear on the first Web Lit Basics I activities in the repo; the remix links appear on all Offline Icebreakers, WLB I, WLB II, Privacy Basics, Make Your First Webpage, IWL I, and IWL II activities.
