### ISSUE TITLE
Side nav loose in new module

### ISSUE THREAD

**Issue by chadsansing** [mozilla/curriculum-final#32]
The side nav is stuttering vertically on-scroll in the activities in this new unit beginning here:

https://mozilla.github.io/curriculum-final/internet-health-basics/session01-intro-to-internet-health.html#overview

cc @flukeout

**Comment by flukeout** [comment]
Are you able to capture a gif of the behaviour as you're seeing it?

I use http://www.cockos.com/licecap/ here's the [download link for mac](http://www.cockos.com/licecap/licecap125.dmg)

Thank you! Also, which browser?

**Comment by chadsansing** [comment]
@flukeout:

![loose-side-nav-1](https://cloud.githubusercontent.com/assets/4128600/23747659/77b36e68-048e-11e7-885f-9a6b139275ea.gif)

**Comment by flukeout** [comment]
@chadsansing Please try again - I updated how that code works and it should resolve this behavior. Give it a test & let me know what you find.

**Comment by chadsansing** [comment]
Passed the test - thanks, @flukeout!
