### ISSUE TITLE
Add landing page to the Repo

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#33]
Navigating to https://mozilla.github.io/curriculum-final/ should have a list of all the activities. Or at least the starting activity for each module. Currently you have to remember the URL, which is hard.

**Comment by chadsansing** [comment]
@hannahkane's work on /activities will make it so the links there go to our curriculum-final links instead of to my curriculum-testing repo, so there will be some accessibility gains there. I would also love a curriculum-final homepage for potential contributors and for the sake of working open.

**Comment by chadsansing** [comment]
@flukeout, maybe this is an opportunity to get funky with new design assets and think of how to minimally adjust the current template for maximum rebrand effect via this homepage design.

This could also let us feature the curriculum-final space as a lab (like with color-picker-snake-game) for activities that don't show up as core curriculum on /activities.
