### ISSUE TITLE
We need a treatment for this difficulty scale that matches the curriculum

### ISSUE THREAD

**Issue by chadsansing** [mozilla/curriculum-final#34]
@flukeout, can we create a treatment of [this document](https://docs.google.com/document/d/1z9UAd21s8FjBxCxfCkK2y-5i4wEeuaM3OkmOtofv7CA/edit) that matches our curriculum templates? 

If we can house it in this repo, I can link to it from each lesson in our Core Curriculum.

Alternatively, we could do a treatment of this page that is more inline with current branding and use it to explore a new curriculum template for after the network site update. I'm not sure what the plans are for "translating" our curriculum into the new branding language.

cc @hannahkane @anmechung @ibgmozilla (someone add Matthew?)

**Comment by hannahkane** [comment]
Adding new branding to the curriculum isn't currently on our roadmap, that I know of. The CoSS team has the search/discovery piece of curriculum on their roadmap, but not the creation workflows, which this would fall under.

I'm starting a more in-depth roadmapping process with OKR group leaders this week. Which OKR would this most relate to?

Idea for solving this problem - should we create a sub-page of the /activities section on the site that includes this content? I believe I could do this myself without needing @flukeout's time. The page could be linked to from each lesson, as you suggested.

**Comment by chadsansing** [comment]
That would be one way to do it, @hannahkane :)

**Comment by hannahkane** [comment]
OK, @chadsansing, if you're okay with that plan, I can create the page soon (probably not today or tomorrow, but I can start Friday). I can't assign this ticket to myself due to lack of permissions, but I'll put this on my own TODO list.

**Comment by chadsansing** [comment]
Thank you, @hannahkane - stellar!

**Comment by hannahkane** [comment]
I took a shot at this, and I'm realizing it's beyond my skillset. Maybe @flukeout should actually look at this. @chadsansing - when do you need this by?

**Comment by chadsansing** [comment]
@hannahkane, @flukeout - the sooner the better. Once we have this, we can link lessons to it and module landing pages to it. This also lets us:

- Further update the module landing pages with new progression copy.
- Create a pedagogy statement page using the same treatment that we can link to in a similar manner from lessons and/or module landing pages.
