### ISSUE TITLE
We need to review and style privacy-rock-paper-scissors

### ISSUE THREAD

**Issue by chadsansing** [mozilla/curriculum-final#36]
Hey, @flukeout - I made a janky rock-paper-scissors engine to jump start our dice game.

- https://github.com/mozilla/curriculum-final/tree/gh-pages/privacy-rock-paper-scissors
- https://mozilla.github.io/curriculum-final/privacy-rock-paper-scissors/index.html

Not sure if this helps or hinders things. Sometimes there's a bug when the more neutral result - I use different passwords vs. I cracked a single password - says, "You lose!", when it should say, "It's a draw!"

Otherwise, needs styling or perhaps a refactoring.

**Comment by flukeout** [comment]
Will check tomorrow when I'm back in action.
