### ISSUE TITLE
Not of a fan of the linked "Web Lit" heading...

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#5]
![image](https://cloud.githubusercontent.com/assets/25212/18593600/01b4f630-7bf1-11e6-9b10-2a1e8e544b13.png)

Feels weird that one heading is blue and linked. What if we add a "see web lit map" type link beside or below the tags instead? 

cc @chadsansing?

**Comment by chadsansing** [comment]
@flukeout - make it so; I agree and would like a better solution.

**Comment by flukeout** [comment]
Will be replacing with...

![image](https://cloud.githubusercontent.com/assets/25212/18643546/7bf5122a-7e5a-11e6-808a-8e0de8310749.png)

**Comment by flukeout** [comment]
Will be replacing all with...

![image](https://cloud.githubusercontent.com/assets/25212/18650754/a20884b2-7e7b-11e6-8946-27ca03900c66.png)

The markup for the categories is...

```
<div weblit-category="read">
  <span>Code</span>
  <span>Design</span>
  <span>Remix</span>
  <span>Design</span>
  <span>Remix</span>
</div>
<div weblit-category="write">
  <span>Code</span>
  <span>Design</span>
  <span>Remix</span>
</div>
<div weblit-category="participate">
  <span>Remix</span>
</div>
```

The **Read**, **Write** & **Participate** headings will be added automatically via CSS.

**Comment by flukeout** [comment]
I'll close this since it's "designed" but I'll need to create a giant QA ticket!
