### ISSUE TITLE
Better treatment for read,write, participate indicator.

### ISSUE THREAD

**Issue by flukeout** [mozilla/curriculum-final#7]
As seen onhttps://mozilla.github.io/curriculum-final/color-picker-challenge/#overview we have...

![image](https://cloud.githubusercontent.com/assets/25212/18641287/d47403ca-7e50-11e6-8a24-36f839d10176.png)

I think we should treat them more similarly to the skills...

![image](https://cloud.githubusercontent.com/assets/25212/18641266/bd358148-7e50-11e6-9988-87a79d6fe7d7.png)

What do you think @chadsansing

Also, what is a good heading for these... **Competencies** ...?

**Comment by chadsansing** [comment]
From MatterMoz:

> Read, write, and participate are like messaging/storytelling verbs we use - categories, I guess?
> 
> Certain web lit skills fall under each, as per the map, but we might editorially label an activity as, say, 1 or 2 verbs, for emphasis even while it has skills from each category.

So...we _could_ create lists of skills under each category name like this (with different treatments for each):

> **Write**
> - Code
> - Compose

Or we could do an inline version with different category and skill treatments like:

> **Write:** code, compose

Regardless, if we provide a category for every skill, we lose ability to emphasize one verb or another for editorial purposes in an activity and, for consistency's sake, we kind of force ourselves to audit and edit the web lit map again to make sure every activity with a skill in a category appears linked to/listed under it. That might not be a bad thing, but it'll take more doing.

Or we could do something like this with a similar box treatment:

> **Web Literacy Categories**
> write, participate
> 
> **Web Literacy Skills**
> code, compose, share

Responses?

**Comment by flukeout** [comment]
I think I like this the most, it will just take more work... 

> **Write:** code, compose

**Comment by flukeout** [comment]
Damn... 

![image](https://cloud.githubusercontent.com/assets/25212/18646890/7b6e36d4-7e68-11e6-9a51-53bf73b69cf8.png)

**Comment by chadsansing** [comment]
But w/ Read first -

**Comment by flukeout** [comment]
I think is what i'm leaning towards...

![image](https://cloud.githubusercontent.com/assets/25212/18649877/d3a9b086-7e76-11e6-9d17-75eb9077f906.png)

What do you think? The red/pink color is kinda neutral here b/c we use it in the sidebar and the description, so I don't feel like it conveys any special meaning or association.

**See it here** - https://mozilla.github.io/curriculum-final/color-picker-challenge/

**Comment by flukeout** [comment]
Done and done. Will fill follow-up ticket to actually apply this to all of the activities - _crikey_

**Comment by chadsansing** [comment]
Looks good! Might be interesting to look at the categories with borders around all sides for comparison.
